const cards = [
  {'value': `Zangief`, 'type':'warrior'},
  {'value': `yeti`, 'type':'warrior'},
  {'value': `water buffalo`, 'type':'warrior'},
  {'value': `Vladmir Putin`, 'type':'warrior'},
  {'value': `two teibbles`, 'type':'warrior'},
  {'value': `trapper`, 'type':'warrior'},
  {'value': `the player to your right`, 'type':'warrior'},
  {'value': `the navy`, 'type':'warrior'},
  {'value': `the common cold`, 'type':'warrior'},
  {'value': `Sylvester Stallone`, 'type':'warrior'},
  {'value': `swarm of piranhas`, 'type':'warrior'},
  {'value': `sushi chef`, 'type':'warrior'},
  {'value': `stegosaurus`, 'type':'warrior'},
  {'value': `star lord`, 'type':'warrior'},
  {'value': `sandy cheeks`, 'type':'warrior'},
  {'value': `Ryu`, 'type':'warrior'},
  {'value': `raccoon`, 'type':'warrior'},
  {'value': `R2D2`, 'type':'warrior'},
  {'value': `prince charming`, 'type':'warrior'},
  {'value': `Predador`, 'type':'warrior'},
  {'value': `poltergeist`, 'type':'warrior'},
  {'value': `Ozzy Osbourne`, 'type':'warrior'},
  {'value': `ocelot`, 'type':'warrior'},
  {'value': `mothra`, 'type':'warrior'},
  {'value': `loch ness monster`, 'type':'warrior'},
  {'value': `literal teen wolf`, 'type':'warrior'},
  {'value': `Legolas`, 'type':'warrior'},
  {'value': `king rather`, 'type':'warrior'},
  {'value': `king Kong`, 'type':'warrior'},
  {'value': `Kid Bengala`, 'type':'warrior'},
  {'value': `keanu reeves`, 'type':'warrior'},
  {'value': `kaiju`, 'type':'warrior'},
  {'value': `Jean Claude Van Damme`, 'type':'warrior'},
  {'value': `iron giant`, 'type':'warrior'},
  {'value': `hydra`, 'type':'warrior'},
  {'value': `honey badger`, 'type':'warrior'},
  {'value': `Hercules`, 'type':'warrior'},
  {'value': `grizzly bear`, 'type':'warrior'},
  {'value': `Goliath`, 'type':'warrior'},
  {'value': `Godzilla`, 'type':'warrior'},
  {'value': `France`, 'type':'warrior'},
  {'value': `Dr. horrible`, 'type':'warrior'},
  {'value': `Dolph Lundgren`, 'type':'warrior'},
  {'value': `Dirty Harry`, 'type':'warrior'},
  {'value': `derby girl`, 'type':'warrior'},
  {'value': `carnivorous plant`, 'type':'warrior'},
  {'value': `Ash`, 'type':'warrior'},
  {'value': `Arnold Schwarzenegger`, 'type':'warrior'},
  {'value': `Army of Skeletons`, 'type':'warrior'},
  {'value': `animorph`, 'type':'warrior'},
  {'value': `amazon warrior`, 'type':'warrior'},
  {'value': `Agent Smith`, 'type':'warrior'},
  {'value': `101 Dalmatians`, 'type':'warrior'},
  {'value': `Abraham Lincoln`, 'type':'warrior'},
  {'value': `alien`, 'type':'warrior'},
  {'value': `angel`, 'type':'warrior'},
  {'value': `apache warrior`, 'type':'warrior'},
  {'value': `assassin`, 'type':'warrior'},
  {'value': `barney`, 'type':'warrior'},
  {'value': `billionaire playboy`, 'type':'warrior'},
  {'value': `blob`, 'type':'warrior'},
  {'value': `bodybuilder`, 'type':'warrior'},
  {'value': `boy band`, 'type':'warrior'},
  {'value': `boy scout`, 'type':'warrior'},
  {'value': `Bruce lee`, 'type':'warrior'},
  {'value': `bull`, 'type':'warrior'},
  {'value': `cactus`, 'type':'warrior'},
  {'value': `Canada`, 'type':'warrior'},
  {'value': `carnie`, 'type':'warrior'},
  {'value': `Cat`, 'type':'warrior'},
  {'value': `cheetah`, 'type':'warrior'},
  {'value': `child beauty pageant queen`, 'type':'warrior'},
  {'value': `chimpanzee`, 'type':'warrior'},
  {'value': `chuck Norris`, 'type':'warrior'},
  {'value': `coachella lineup`, 'type':'warrior'},
  {'value': `College A Cappella Group`, 'type':'warrior'},
  {'value': `Conan`, 'type':'warrior'},
  {'value': `conjoined twins`, 'type':'warrior'},
  {'value': `cowboy`, 'type':'warrior'},
  {'value': `crazy cat lady`, 'type':'warrior'},
  {'value': `Crocodile Hunter`, 'type':'warrior'},
  {'value': `Darth Vader`, 'type':'warrior'},
  {'value': `demon`, 'type':'warrior'},
  {'value': `demon-possessed car`, 'type':'warrior'},
  {'value': `dexter`, 'type':'warrior'},
  {'value': `Disembodied Head`, 'type':'warrior'},
  {'value': `dolphin`, 'type':'warrior'},
  {'value': `dragon`, 'type':'warrior'},
  {'value': `E.T.`, 'type':'warrior'},
  {'value': `Eagle`, 'type':'warrior'},
  {'value': `Electric Eel`, 'type':'warrior'},
  {'value': `Emperor Penguin`, 'type':'warrior'},
  {'value': `everyone at burning man`, 'type':'warrior'},
  {'value': `evil doll`, 'type':'warrior'},
  {'value': `fainting goat`, 'type':'warrior'},
  {'value': `femme fatale`, 'type':'warrior'},
  {'value': `Forrest Gump`, 'type':'warrior'},
  {'value': `Frankenstein`, 'type':'warrior'},
  {'value': `Freddy`, 'type':'warrior'},
  {'value': `French bulldog`, 'type':'warrior'},
  {'value': `Gandhi`, 'type':'warrior'},
  {'value': `Genghis Khan`, 'type':'warrior'},
  {'value': `George W. Bush`, 'type':'warrior'},
  {'value': `giant squid`, 'type':'warrior'},
  {'value': `giraffe`, 'type':'warrior'},
  {'value': `girl scout`, 'type':'warrior'},
  {'value': `gladiator`, 'type':'warrior'},
  {'value': `Google`, 'type':'warrior'},
  {'value': `gorilla`, 'type':'warrior'},
  {'value': `grim reaper`, 'type':'warrior'},
  {'value': `Hannibal`, 'type':'warrior'},
  {'value': `Heisenberg`, 'type':'warrior'},
  {'value': `Helen Keller`, 'type':'warrior'},
  {'value': `Hermione`, 'type':'warrior'},
  {'value': `high school marching band`, 'type':'warrior'},
  {'value': `Hillary Clinton`, 'type':'warrior'},
  {'value': `hippo`, 'type':'warrior'},
  {'value': `hipster`, 'type':'warrior'},
  {'value': `hobo`, 'type':'warrior'},
  {'value': `hockey player`, 'type':'warrior'},
  {'value': `homer`, 'type':'warrior'},
  {'value': `hulk`, 'type':'warrior'},
  {'value': `Hunchback`, 'type':'warrior'},
  {'value': `identical twins`, 'type':'warrior'},
  {'value': `iron man`, 'type':'warrior'},
  {'value': `jack bauer`, 'type':'warrior'},
  {'value': `Jason`, 'type':'warrior'},
  {'value': `Justin bieber`, 'type':'warrior'},
  {'value': `k-pop star`, 'type':'warrior'},
  {'value': `Katniss`, 'type':'warrior'},
  {'value': `Kindergarten Class`, 'type':'warrior'},
  {'value': `leprechaun`, 'type':'warrior'},
  {'value': `Literally Insane Clown Posse`, 'type':'warrior'},
  {'value': `Lucha Libre Wrestler`, 'type':'warrior'},
  {'value': `macgyver`, 'type':'warrior'},
  {'value': `mad scientist`, 'type':'warrior'},
  {'value': `mafia don`, 'type':'warrior'},
  {'value': `Mario Brothers.`, 'type':'warrior'},
  {'value': `marshmallow man`, 'type':'warrior'},
  {'value': `Martha Stewart`, 'type':'warrior'},
  {'value': `me`, 'type':'warrior'},
  {'value': `Meat Loaf`, 'type':'warrior'},
  {'value': `men in black`, 'type':'warrior'},
  {'value': `mermaid`, 'type':'warrior'},
  {'value': `Michael Jackson`, 'type':'warrior'},
  {'value': `mike Tyson`, 'type':'warrior'},
  {'value': `Miley Cyrus`, 'type':'warrior'},
  {'value': `mime`, 'type':'warrior'},
  {'value': `moose`, 'type':'warrior'},
  {'value': `Mr. Rogers`, 'type':'warrior'},
  {'value': `mummy`, 'type':'warrior'},
  {'value': `Musketeer`, 'type':'warrior'},
  {'value': `my boss`, 'type':'warrior'},
  {'value': `my ex`, 'type':'warrior'},
  {'value': `my significant other`, 'type':'warrior'},
  {'value': `Nigerian prince`, 'type':'warrior'},
  {'value': `ninja`, 'type':'warrior'},
  {'value': `nudist`, 'type':'warrior'},
  {'value': `Obama`, 'type':'warrior'},
  {'value': `octopus`, 'type':'warrior'},
  {'value': `Olympic gymnast`, 'type':'warrior'},
  {'value': `Owl`, 'type':'warrior'},
  {'value': `pet rock`, 'type':'warrior'},
  {'value': `pick a celebrity`, 'type':'warrior'},
  {'value': `pick a comic book character`, 'type':'warrior'},
  {'value': `pick a movie character`, 'type':'warrior'},
  {'value': `pick a TV character`, 'type':'warrior'},
  {'value': `pick an action movie star`, 'type':'warrior'},
  {'value': `pirate`, 'type':'warrior'},
  {'value': `Polar Bear`, 'type':'warrior'},
  {'value': `psychic`, 'type':'warrior'},
  {'value': `pterodactyl`, 'type':'warrior'},
  {'value': `Pikachu`, 'type':'warrior'},
  {'value': `queen`, 'type':'warrior'},
  {'value': `Rambo`, 'type':'warrior'},
  {'value': `redneck`, 'type':'warrior'},
  {'value': `Reggae Band`, 'type':'warrior'},
  {'value': `Rhinoceros`, 'type':'warrior'},
  {'value': `Robin Hood`, 'type':'warrior'},
  {'value': `robot`, 'type':'warrior'},
  {'value': `saber-toothed tiger`, 'type':'warrior'},
  {'value': `samurai`, 'type':'warrior'},
  {'value': `Sasquatch`, 'type':'warrior'},
  {'value': `secret agent`, 'type':'warrior'},
  {'value': `senior citizen bowling team`, 'type':'warrior'},
  {'value': `shark`, 'type':'warrior'},
  {'value': `sharpshooter`, 'type':'warrior'},
  {'value': `Sherlock Holmes`, 'type':'warrior'},
  {'value': `skeleton`, 'type':'warrior'},
  {'value': `sloth`, 'type':'warrior'},
  {'value': `smoke monster`, 'type':'warrior'},
  {'value': `snake`, 'type':'warrior'},
  {'value': `soccer mom`, 'type':'warrior'},
  {'value': `spartan`, 'type':'warrior'},
  {'value': `spider`, 'type':'warrior'},
  {'value': `Stephen Hawking`, 'type':'warrior'},
  {'value': `street fighter`, 'type':'warrior'},
  {'value': `sumo wrestler`, 'type':'warrior'},
  {'value': `supermodel`, 'type':'warrior'},
  {'value': `swarm of killer bees`, 'type':'warrior'},
  {'value': `t-rex`, 'type':'warrior'},
  {'value': `Terminator`, 'type':'warrior'},
  {'value': `the devil`, 'type':'warrior'},
  {'value': `the doctor`, 'type':'warrior'},
  {'value': `the dude`, 'type':'warrior'},
  {'value': `the Illuminati`, 'type':'warrior'},
  {'value': `the kardashians`, 'type':'warrior'},
  {'value': `the player to your left`, 'type':'warrior'},
  {'value': `the pope`, 'type':'warrior'},
  {'value': `The Statue of library`, 'type':'warrior'},
  {'value': `The U.N.`, 'type':'warrior'},
  {'value': `turtle`, 'type':'warrior'},
  {'value': `ultimate fighting champion`, 'type':'warrior'},
  {'value': `unicorn`, 'type':'warrior'},
  {'value': `vampire`, 'type':'warrior'},
  {'value': `vampire slayer`, 'type':'warrior'},
  {'value': `vegan`, 'type':'warrior'},
  {'value': `velociraptor`, 'type':'warrior'},
  {'value': `viking`, 'type':'warrior'},
  {'value': `werewolf`, 'type':'warrior'},
  {'value': `Whale`, 'type':'warrior'},
  {'value': `willy wonka`, 'type':'warrior'},
  {'value': `witch`, 'type':'warrior'},
  {'value': `Wizard`, 'type':'warrior'},
  {'value': `wooly mammoth`, 'type':'warrior'},
  {'value': `Your Mom`, 'type':'warrior'},
  {'value': `Zombie`, 'type':'warrior'},
  {'value': `wrapped in toilet paper`, 'type':'trait'},
  {'value': `wearing a scuba suit`, 'type':'trait'},
  {'value': `wearing a bubble wrap suit`, 'type':'trait'},
  // {'value': `using a_ as a club draw a random character card`, 'type':'trait'},
  {'value': `throws water balloons filled with acid`, 'type':'trait'},
  {'value': `swinging a two-ton tuna`, 'type':'trait'},
  {'value': `stuck in one of those electric cars for toddlers`, 'type':'trait'},
  {'value': `shoots lasers out of ears`, 'type':'trait'},
  {'value': `riding a nuclear missile`, 'type':'trait'},
  {'value': `regrows body parts at will`, 'type':'trait'},
  {'value': `machine guns for legs`, 'type':'trait'},
  {'value': `literally a gift`, 'type':'trait'},
  {'value': `leading a team of trained velociraptors`, 'type':'trait'},
  {'value': `It has six nipples`, 'type':'trait'},
  {'value': `is really really good at parkour ...really`, 'type':'trait'},
  {'value': `is really really emotional`, 'type':'trait'},
  {'value': `is faster than a speeding bullet`, 'type':'trait'},
  {'value': `Inflates when threatened`, 'type':'trait'},
  {'value': `in a flying saucer`, 'type':'trait'},
  {'value': `Have penises instead of fingers`, 'type':'trait'},
  {'value': `Has wings, but can't fly`, 'type':'trait'},
  {'value': `Has the power to have all the powers`, 'type':'trait'},
  {'value': `Has the MIB memory eraser, but has no dark glasses`, 'type':'trait'},
  {'value': `has an enormous exposed brain`, 'type':'trait'},
  {'value': `Has a genie that makes a wish`, 'type':'trait'},
  {'value': `flaming hands`, 'type':'trait'},
  {'value': `everything they touch turns inside out`, 'type':'trait'},
  {'value': `Driving a Dodge Charger`, 'type':'trait'},
  {'value': `covered in gasoline`, 'type':'trait'},
  {'value': `commands an amry of disposable minions`, 'type':'trait'},
  {'value': `chained to their evil twin`, 'type':'trait'},
  {'value': `cannons instead of hands`, 'type':'trait'},
  {'value': `Can transform coca into pepsi`, 'type':'trait'},
  {'value': `can summon infinite trampolines`, 'type':'trait'},
  {'value': `Can predict events after they happen`, 'type':'trait'},
  {'value': `can only be killer by a stake through the heart`, 'type':'trait'},
  {'value': `can only be killer by a shot to the head`, 'type':'trait'},
  {'value': `can leap over tall buildings in a single bound`, 'type':'trait'},
  {'value': `Can grow a second nose anywhere on your body`, 'type':'trait'},
  {'value': `can fly...at the speed of molasses`, 'type':'trait'},
  {'value': `can call orbital bombardments`, 'type':'trait'},
  // {'value': `bitten by a radioactive_ draw a random character card`, 'type':'trait'},
  {'value': `armer with a limitless loot crate`, 'type':'trait'},
  {'value': `armed with a surface-to-air missile launcher`, 'type':'trait'},
  {'value': `armed with a really really bright laser pointer`, 'type':'trait'},
  {'value': `armed with a railgun`, 'type':'trait'},
  {'value': `armed with a piranha launcher`, 'type':'trait'},
  {'value': `armed with a machete`, 'type':'trait'},
  {'value': `armed with a lightsaber that has two smaller lightsabers sticking out of the hilt`, 'type':'trait'},
  {'value': `armed with a Gatling gun`, 'type':'trait'},
  {'value': `armed with a dubstep gun`, 'type':'trait'},
  {'value': `Ability to play perfectly any musical instrument`, 'type':'trait'},
  {'value': `9 feet tall`, 'type':'trait'},
  {'value': `6 inches tall`, 'type':'trait'},
  {'value': `50 of them`, 'type':'trait'},
  {'value': `3-foot fingernails`, 'type':'trait'},
  {'value': `3 stories tall`, 'type':'trait'},
  {'value': `3 of them`, 'type':'trait'},
  {'value': `100 stories tall`, 'type':'trait'},
  {'value': `100 of them`, 'type':'trait'},
  {'value': `10 stories tall`, 'type':'trait'},
  {'value': `10 of them`, 'type':'trait'},
  {'value': `acid blood`, 'type':'trait'},
  {'value': `afraid of water`, 'type':'trait'},
  {'value': `agoraphobic`, 'type':'trait'},
  {'value': `allergic to all animals`, 'type':'trait'},
  {'value': `armed with a bacon-wrapped baseball bat`, 'type':'trait'},
  {'value': `armed with a barbed wore net`, 'type':'trait'},
  {'value': `armed with a cannon`, 'type':'trait'},
  {'value': `armed with a catapult and unlimited livestock`, 'type':'trait'},
  {'value': `armed with a cattle prod`, 'type':'trait'},
  {'value': `armed with a chainsaw`, 'type':'trait'},
  {'value': `armed with a crowbar`, 'type':'trait'},
  {'value': `armed with a flamethrower`, 'type':'trait'},
  {'value': `armed with a freeze ray`, 'type':'trait'},
  {'value': `armed with a harpoon gun`, 'type':'trait'},
  {'value': `armed with a lightsaber`, 'type':'trait'},
  {'value': `armed with a live t-rex on a stick`, 'type':'trait'},
  {'value': `armed with a long electrified whip`, 'type':'trait'},
  {'value': `armed with a machine gun`, 'type':'trait'},
  {'value': `armed with a nail gun`, 'type':'trait'},
  {'value': `armed with a poison-tipped lance`, 'type':'trait'},
  {'value': `armed with a portal gun`, 'type':'trait'},
  {'value': `armed with a puppy musket`, 'type':'trait'},
  {'value': `armed with a rocket launcher`, 'type':'trait'},
  {'value': `armed with a sadness ray`, 'type':'trait'},
  {'value': `armed with a samurai sword`, 'type':'trait'},
  {'value': `armed with a shotgun`, 'type':'trait'},
  {'value': `armed with a shotgun that shoots shotguns`, 'type':'trait'},
  {'value': `armed with a shrink ray`, 'type':'trait'},
  {'value': `armed with a sniper rifle`, 'type':'trait'},
  {'value': `armed with a superglue fire hose`, 'type':'trait'},
  {'value': `armed with a tranquilizer gun`, 'type':'trait'},
  {'value': `armed with a trident`, 'type':'trait'},
  {'value': `armed with an impenetrable shield`, 'type':'trait'},
  {'value': `armed with an infinite sausage lasso`, 'type':'trait'},
  {'value': `armed with Axe`, 'type':'trait'},
  {'value': `armed with catarangs`, 'type':'trait'},
  {'value': `armed with Cupid's bow`, 'type':'trait'},
  {'value': `armed with dynamite`, 'type':'trait'},
  {'value': `armed with ghost pepper spray`, 'type':'trait'},
  {'value': `armed with holy hand grenades`, 'type':'trait'},
  {'value': `armed with nunchucks`, 'type':'trait'},
  {'value': `armer with a bow and unlimited arrows`, 'type':'trait'},
  {'value': `balancing on a circus ball`, 'type':'trait'},
  {'value': `being guarded by the secret service`, 'type':'trait'},
  {'value': `believes they are invisible`, 'type':'trait'},
  {'value': `bionic`, 'type':'trait'},
  // {'value': `bottom half is_ draw another character card from the deck`, 'type':'trait'},
  // {'value': `bottom half is_ play another character card from hand`, 'type':'trait'},
  // {'value': `bottom half is_ play another character card from the deck`, 'type':'trait'},
  {'value': `breathes fire`, 'type':'trait'},
  {'value': `can animate dirt`, 'type':'trait'},
  {'value': `can become any animal`, 'type':'trait'},
  {'value': `can become mist while holding breath`, 'type':'trait'},
  {'value': `can blow 200-mph winds`, 'type':'trait'},
  {'value': `can breathe underwater`, 'type':'trait'},
  // {'value': `can change into a_ at will pick a character card from your hand`, 'type':'trait'},
  // {'value': `can change into a_at will. pick a character card from your hand`, 'type':'trait'},
  {'value': `can clone self but each clone is half as smart as the previous`, 'type':'trait'},
  {'value': `can clone self but each clone is half the size of the previous`, 'type':'trait'},
  {'value': `can control gravity`, 'type':'trait'},
  {'value': `can control hair`, 'type':'trait'},
  {'value': `can control machines`, 'type':'trait'},
  {'value': `can control opponent's right hand`, 'type':'trait'},
  {'value': `can control plants`, 'type':'trait'},
  {'value': `can create a hologram of self`, 'type':'trait'},
  {'value': `can dig and run through tunnels with super speed`, 'type':'trait'},
  {'value': `can fly`, 'type':'trait'},
  {'value': `can fly but only two feet above the ground`, 'type':'trait'},
  {'value': `can fly if nobody is watching`, 'type':'trait'},
  {'value': `can hold breathe forever`, 'type':'trait'},
  {'value': `can kill with a kiss`, 'type':'trait'},
  {'value': `can make a force field while holding breath`, 'type':'trait'},
  {'value': `can match opponent's size`, 'type':'trait'},
  {'value': `can only be killed by beheading`, 'type':'trait'},
  {'value': `can only move by back flipping`, 'type':'trait'},
  {'value': `can only move when opponent moves`, 'type':'trait'},
  {'value': `can only see movement`, 'type':'trait'},
  {'value': `can possess opponent for 30 seconds then gets very tired`, 'type':'trait'},
  {'value': `can read minds`, 'type':'trait'},
  {'value': `can run 200 mph but only in a straight line`, 'type':'trait'},
  {'value': `can see 3 seconds into the future`, 'type':'trait'},
  {'value': `can stop time while holding breath`, 'type':'trait'},
  {'value': `can stretch like rubber`, 'type':'trait'},
  {'value': `can summon am army internet trolls`, 'type':'trait'},
  {'value': `can summon anything from a hardware store`, 'type':'trait'},
  {'value': `can take the form of anything the touch`, 'type':'trait'},
  {'value': `can take the form of anything water-based`, 'type':'trait'},
  {'value': `can teleport but goes blind for 10 seconds after each use`, 'type':'trait'},
  {'value': `can throw sticky bombs`, 'type':'trait'},
  {'value': `can turn into any vehicle`, 'type':'trait'},
  {'value': `can turn invisible while singing snow tunes`, 'type':'trait'},
  {'value': `can turn to steel`, 'type':'trait'},
  {'value': `can walk through solid objects`, 'type':'trait'},
  {'value': `can't see`, 'type':'trait'},
  {'value': `can't stop clapping`, 'type':'trait'},
  {'value': `can't stop dancing`, 'type':'trait'},
  {'value': `can't stop laughing`, 'type':'trait'},
  {'value': `can't stop sobbing`, 'type':'trait'},
  {'value': `can't turn left`, 'type':'trait'},
  {'value': `carrying a baby`, 'type':'trait'},
  {'value': `carrying way too many grocery bags`, 'type':'trait'},
  {'value': `catlike reflexes`, 'type':'trait'},
  {'value': `clothes are way too big`, 'type':'trait'},
  {'value': `clothes are way too tight`, 'type':'trait'},
  {'value': `constantly taking selfies`, 'type':'trait'},
  {'value': `controls a tween army`, 'type':'trait'},
  {'value': `controls all animals`, 'type':'trait'},
  {'value': `controls an army of flying monkeys`, 'type':'trait'},
  {'value': `controls magnetism`, 'type':'trait'},
  {'value': `controls weather`, 'type':'trait'},
  {'value': `covered in eyes`, 'type':'trait'},
  {'value': `covered in spikes`, 'type':'trait'},
  {'value': `distracted by shiny things`, 'type':'trait'},
  // {'value': `draw a character card as your 500-pound pet`, 'type':'trait'},
  // {'value': `draw a new character card with one new attribute as sidekick`, 'type':'trait'},
  // {'value': `draw a new character card with one new attribute as your sidekick`, 'type':'trait'},
  // {'value': `draw and play two random attributes from the deck discard this card after use`, 'type':'trait'},
  {'value': `driving a tank`, 'type':'trait'},
  {'value': `driving popemobile`, 'type':'trait'},
  {'value': `duplicate one opponent attribute`, 'type':'trait'},
  {'value': `eliminate all attributes in this fight`, 'type':'trait'},
  {'value': `entire body is very sticky`, 'type':'trait'},
  {'value': `everything the touch turns to hummus`, 'type':'trait'},
  {'value': `explodes if the stop moving`, 'type':'trait'},
  {'value': `figuratively "on fire" ...and literally`, 'type':'trait'},
  {'value': `floating down on a parachute`, 'type':'trait'},
  {'value': `frost breath`, 'type':'trait'},
  {'value': `handcuffed to golf cart`, 'type':'trait'},
  {'value': `hands are covered in butter`, 'type':'trait'},
  {'value': `hands glued to hips`, 'type':'trait'},
  {'value': `has a 6-foot neck`, 'type':'trait'},
  {'value': `has a battleship`, 'type':'trait'},
  {'value': `has a beard made bees`, 'type':'trait'},
  {'value': `has a hostage`, 'type':'trait'},
  {'value': `has a magical unicorn horn`, 'type':'trait'},
  {'value': `has a skunk on a stick`, 'type':'trait'},
  {'value': `has a time machine phone booth`, 'type':'trait'},
  {'value': `has a voodoo doll of opponent`, 'type':'trait'},
  {'value': `has an invisible cloak`, 'type':'trait'},
  {'value': `has an invisible jet`, 'type':'trait'},
  {'value': `has feet instead of hands`, 'type':'trait'},
  {'value': `has hands instead of feet`, 'type':'trait'},
  {'value': `has jellyfish instead of hands`, 'type':'trait'},
  {'value': `has majestic flamming antlers growing of head`, 'type':'trait'},
  {'value': `has no bones`, 'type':'trait'},
  {'value': `has one tiny baby arm`, 'type':'trait'},
  {'value': `has telekinesis`, 'type':'trait'},
  {'value': `has tiny bird legs`, 'type':'trait'},
  {'value': `has tiny t-rex arms`, 'type':'trait'},
  {'value': `has two extra arms`, 'type':'trait'},
  {'value': `has two peg legs`, 'type':'trait'},
  {'value': `has vertigo`, 'type':'trait'},
  {'value': `has x-ray vision`, 'type':'trait'},
  {'value': `heals 100 times faster than normal`, 'type':'trait'},
  {'value': `horrible self-esteem`, 'type':'trait'},
  {'value': `I'm a berserker rage`, 'type':'trait'},
  {'value': `in a blimp`, 'type':'trait'},
  {'value': `in a helicopter`, 'type':'trait'},
  {'value': `in a hot air balloon`, 'type':'trait'},
  {'value': `in a jet fighter`, 'type':'trait'},
  {'value': `in a space suit`, 'type':'trait'},
  {'value': `inside a giant hamster ball`, 'type':'trait'},
  // {'value': `inside a giant robotic_ draw a random character card`, 'type':'trait'},
  // {'value': `inside a giant robotic_ pick a character card from your hand`, 'type':'trait'},
  {'value': `invisible`, 'type':'trait'},
  {'value': `is a 1000 years old`, 'type':'trait'},
  {'value': `is a baby`, 'type':'trait'},
  {'value': `is a belieber and is convinced opponent means bieber bodily harm`, 'type':'trait'},
  {'value': `is a hoarder`, 'type':'trait'},
  {'value': `is a hypnotist`, 'type':'trait'},
  {'value': `is a piñata`, 'type':'trait'},
  {'value': `is a stuffed`, 'type':'trait'},
  {'value': `is a super genius`, 'type':'trait'},
  {'value': `is a tween`, 'type':'trait'},
  {'value': `is amish`, 'type':'trait'},
  {'value': `is drunk`, 'type':'trait'},
  {'value': `is elderly`, 'type':'trait'},
  {'value': `is having a really good hair day`, 'type':'trait'},
  {'value': `is made of guacamole`, 'type':'trait'},
  {'value': `is rabid`, 'type':'trait'},
  {'value': `is radioactive`, 'type':'trait'},
  {'value': `is really hangry`, 'type':'trait'},
  {'value': `is really into fonts`, 'type':'trait'},
  {'value': `is really really good-looking`, 'type':'trait'},
  {'value': `is really really stupid`, 'type':'trait'},
  {'value': `just drank five energy drinks`, 'type':'trait'},
  {'value': `killed by water`, 'type':'trait'},
  {'value': `knows knug fu`, 'type':'trait'},
  {'value': `laser eyes`, 'type':'trait'},
  {'value': `lays exploding eggs`, 'type':'trait'},
  {'value': `leeches opponent's health when touched`, 'type':'trait'},
  {'value': `literal jazz hands`, 'type':'trait'},
  {'value': `literally wearing beer goggles`, 'type':'trait'},
  {'value': `literally wearing heart on sleeve`, 'type':'trait'},
  {'value': `locked in a antique diver's helmet`, 'type':'trait'},
  {'value': `locked in a shark cage`, 'type':'trait'},
  {'value': `long metal claws pop out of hands`, 'type':'trait'},
  {'value': `made of lava`, 'type':'trait'},
  {'value': `made of mirrors`, 'type':'trait'},
  {'value': `made of paper`, 'type':'trait'},
  {'value': `made of sand`, 'type':'trait'},
  {'value': `made of stone`, 'type':'trait'},
  {'value': `megafighter!`, 'type':'trait'},
  {'value': `morbidly obese`, 'type':'trait'},
  {'value': `mustache can stretch and move at will`, 'type':'trait'},
  {'value': `narcoleptic`, 'type':'trait'},
  {'value': `no arms`, 'type':'trait'},
  {'value': `no depth perception`, 'type':'trait'},
  {'value': `no legs`, 'type':'trait'},
  {'value': `on a jet ski`, 'type':'trait'},
  {'value': `on a pogo stick`, 'type':'trait'},
  {'value': `on a segway`, 'type':'trait'},
  {'value': `on a velocipede`, 'type':'trait'},
  {'value': `on stilts`, 'type':'trait'},
  {'value': `only has one leg`, 'type':'trait'},
  {'value': `pacifist`, 'type':'trait'},
  {'value': `piloting an attack drone`, 'type':'trait'},
  {'value': `pregnant`, 'type':'trait'},
  {'value': `really clumsy`, 'type':'trait'},
  {'value': `really really has to pee`, 'type':'trait'},
  {'value': `relies on heat vision to see`, 'type':'trait'},
  {'value': `relies on sonar to see`, 'type':'trait'},
  {'value': `riding a battle cat`, 'type':'trait'},
  {'value': `riding a broomstick`, 'type':'trait'},
  {'value': `riding a depressed centaur`, 'type':'trait'},
  {'value': `riding a flying narwhal`, 'type':'trait'},
  {'value': `riding a horse`, 'type':'trait'},
  {'value': `riding a hoverboard`, 'type':'trait'},
  {'value': `riding a motorcycle`, 'type':'trait'},
  {'value': `riding a war elephant`, 'type':'trait'},
  // {'value': `riding a_ draw a character from the deck`, 'type':'trait'},
  {'value': `scissor hands`, 'type':'trait'},
  {'value': `screams names of attacks before using them`, 'type':'trait'},
  {'value': `shoots acid`, 'type':'trait'},
  {'value': `shoots bees from mouth`, 'type':'trait'},
  {'value': `shoots blinding light from hands`, 'type':'trait'},
  {'value': `shoots glitter`, 'type':'trait'},
  {'value': `shoots laughing gas`, 'type':'trait'},
  {'value': `shoots lightning`, 'type':'trait'},
  {'value': `shoots poison darts from nose`, 'type':'trait'},
  {'value': `shoots tear gas`, 'type':'trait'},
  {'value': `shoots webs`, 'type':'trait'},
  {'value': `slows time when eyes are closed`, 'type':'trait'},
  {'value': `sonic scream`, 'type':'trait'},
  {'value': `sprays neurotoxin`, 'type':'trait'},
  {'value': `steal one attribute from opponent`, 'type':'trait'},
  {'value': `steal one attribute from opponent discard this card after use`, 'type':'trait'},
  {'value': `steals opponent's abilities with a touch`, 'type':'trait'},
  {'value': `stone gaze`, 'type':'trait'},
  {'value': `suffering from delusions of grandeur`, 'type':'trait'},
  {'value': `summons cats to do bidding`, 'type':'trait'},
  {'value': `super endurance`, 'type':'trait'},
  {'value': `super jump`, 'type':'trait'},
  {'value': `super strength`, 'type':'trait'},
  {'value': `swinging a shark on a chain`, 'type':'trait'},
  {'value': `thinks the floor is actually lava`, 'type':'trait'},
  {'value': `throwing spears`, 'type':'trait'},
  {'value': `throws 200-mph fastballs`, 'type':'trait'},
  {'value': `throws antiques`, 'type':'trait'},
  {'value': `throws bears`, 'type':'trait'},
  {'value': `throws burritos`, 'type':'trait'},
  {'value': `throws fireballs`, 'type':'trait'},
  {'value': `throws knives`, 'type':'trait'},
  {'value': `throws ninja stars`, 'type':'trait'},
  {'value': `tongue can stretch and move at will`, 'type':'trait'},
  // {'value': `top half is_ draw another character card from the deck`, 'type':'trait'},
  // {'value': `top half is_ play another character card from hand`, 'type':'trait'},
  {'value': `trapped in a potato sack`, 'type':'trait'},
  {'value': `two extra legs`, 'type':'trait'},
  {'value': `unaffected by impact`, 'type':'trait'},
  {'value': `used to be a bear`, 'type':'trait'},
  {'value': `uses the force`, 'type':'trait'},
  {'value': `venomous bite`, 'type':'trait'},
  {'value': `walking twelve wiener dogs`, 'type':'trait'},
  {'value': `wall-crawler`, 'type':'trait'},
  {'value': `wearing a flaming tutu`, 'type':'trait'},
  {'value': `wearing a impenetrable tuxedo`, 'type':'trait'},
  {'value': `wearing a jetpack`, 'type':'trait'},
  {'value': `wearing a meat bikini`, 'type':'trait'},
  {'value': `wearing a robotic exoskeleton`, 'type':'trait'},
  {'value': `wearing a suit of armor`, 'type':'trait'},
  {'value': `wearing a tin foil hat`, 'type':'trait'},
  {'value': `wearing cement shoes`, 'type':'trait'},
  {'value': `wearing one of those comes they put on pets to keep them from licking themselves`, 'type':'trait'},
  {'value': `wearing rocket-powered roller skates`, 'type':'trait'},
  {'value': `wearing sharpened stilettos`, 'type':'trait'},
  {'value': `wearing skis`, 'type':'trait'},
  {'value': `with a prehensile tail`, 'type':'trait'},
  {'value': `undersea research station`, 'type':'setting'},
  {'value': `the slope of an erupting volcano`, 'type':'setting'},
  {'value': `On top of a skyscraper`, 'type':'setting'},
  {'value': `on a roller coaster`, 'type':'setting'},
  {'value': `On a nudist beach`, 'type':'setting'},
  {'value': `old rope bridge over lava`, 'type':'setting'},
  {'value': `Nazi Lunar Base`, 'type':'setting'},
  {'value': `mars colony`, 'type':'setting'},
  {'value': `Inside a bus that cannot slow down unless it explodes`, 'type':'setting'},
  {'value': `In the middle of the desert`, 'type':'setting'},
  {'value': `In the London Underground`, 'type':'setting'},
  {'value': `In outer space`, 'type':'setting'},
  {'value': `Godzilla's stomach`, 'type':'setting'},
  {'value': `desert island`, 'type':'setting'},
  {'value': `deep in the amazon rainforest`, 'type':'setting'},
  {'value': `Dangerously close to a black hole`, 'type':'setting'},
  {'value': `crashing airplane with one parachute`, 'type':'setting'},
  {'value': `dessert island`, 'type':'setting'},
  {'value': `Zombie apocalypse`, 'type':'modification'},
  {'value': `The place will self-destruct in 5 minutes`, 'type':'modification'},
  {'value': `The place is being invaded by demons`, 'type':'modification'},
  {'value': `Morgan Freeman is narrating the battle and everyone can hear him`, 'type':'modification'},
  {'value': `Literally raining pocketknives`, 'type':'modification'},
  {'value': `gravity is reversed`, 'type':'modification'},
  // {'value': `fighting for custody of_ on court TV draw a random character card`, 'type':'modification'},
  {'value': `fighters cannot see or hear`, 'type':'modification'},
  // {'value': `fighters are riding giant _sn draw a random character card`, 'type':'modification'},
  {'value': `fighters are jousting`, 'type':'modification'},
  // {'value': `fighters are inside giant robotic _s draw a random character card`, 'type':'modification'},
  {'value': `fighters are bungee jumping next to each other`, 'type':'modification'},
  {'value': `Everyone is competing on Rainbow Road`, 'type':'modification'},
  {'value': `Everyone is chasing a cheese wheel down the hill`, 'type':'modification'},
  {'value': `Everyone is being chased by the border patrol`, 'type':'modification'},
  {'value': `All fighters armed with gasoline squirt guns`, 'type':'modification'},
  {'value': `all fighters armed with chainsaws`, 'type':'modification'},
  {'value': `all fighters are in helicopters`, 'type':'modification'},
]

const warriors = cards.filter(c => c.type === 'warrior')
const traits = cards.filter(c => c.type === 'trait')
const modifications = cards.filter(c => c.type === 'modification')
const settings = cards.filter(c => c.type === 'setting')

export { cards, warriors, traits, modifications, settings }